apiVersion: v1
kind: ServiceAccount
metadata:
  name: hazelcast-operator

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hazelcast-operator
subjects:
- kind: ServiceAccount
  name: hazelcast-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
